sitegroup: d7-starter
deploy_tasks:
  development:
    before_deploy:
      - yarn install
      - yarn run gulp -- compile
    after_deploy:
      - drush -y cc css-js
  production:
    before_deploy:
      - yarn install
      - yarn run gulp -- build
      - rm -rf node_modules
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc all
shared:
  production:
    - src: files
      dst: sites/default/files

