deploy_tasks:
  development:
    before_deploy:
      - npm install
      - npm run gulp -- compile
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc css-js
  production:
    before_deploy:
      - npm install
      - npm run gulp -- build
      - rm -rf node_modules
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc css-js

shared:
  production:
    - src: files
      dst: sites/default/files
