deploy_tasks:
  development:
    before_deploy: |
      npm install 2>&1
      npm run gulp -- compile 2>&1
    after_deploy: |
      drush cc css-js -y 2>&1
  production:
    before_deploy: |
      npm install 2>&1
      npm run gulp -- build 2>&1
    after_deploy: |
      drush updb -y 2>&1
      
branch_deploy_tasks:
  dropguard:
    before_deploy: |
      drush sql-drop -y 2>&1
      drush sql-sync @prod default -y 2>&1
      drush rsync @prod:%files default:%files -y 2>&1

shared:
  production:
    - src: files
      dst: sites/default/files
